### ISSUE TITLE
Difficulty running on Windows 10

### ISSUE THREAD

**Issue by gi-jimbo** [marialarsson/tsugite#6]
I downloaded the Windows exe and when I try to run it I get the following error.
![Tsugite_app Error](https://user-images.githubusercontent.com/65555733/98399210-4c3be200-201f-11eb-88a0-a0b721b81ae5.png)
I have Python 3.8.6 installed.

**Comment by gi-jimbo** [comment]
Due to the issues I was having with the exe file, I've resorted to trying to run the python script directly.

**Comment by marialarsson** [comment]
@gi-jimbo thank you for sharing this issue and sorry for the very slow reply! This screenshot helped us to narrow down what is the issue with running the executable file. We think it was the shader version. So we have now downgraded the shader to an earlier, more stable version, and made a new executable. Direkt download link here: http://ma-la.com/Tsugite_1.0.1.zip
Please try it. And we are curious to find out if it worked or not, so please share! Thank you

**Comment by marialarsson** [comment]
I got response from a number of people that previously could not open the executable that it worked. So I will close this issue.
