### ISSUE TITLE
Unable to load numpy_formathandler accelerator from OpenGL_accelerate

### ISSUE THREAD

**Issue by gi-jimbo** [marialarsson/tsugite#7]
I'm getting the error above when trying to run the Tsugite_app.py script.  
When I run: pip install PyOpenGL it says I already have 3.1.5
When I run: pip install PyOpenGL_accelerate it says I already have 3.1.5
When I run: pip install numpy it says I have 1.19.5
When I run: pip install numpy 1.18.5 it says could not find a version that satisfies the requirement 1.18.5 and no matching distribution found for 1.18.5

For reference, here's my full pip list:
Package             Version
------------------- -------
cycler              0.10.0
kiwisolver          1.3.1
matplotlib          3.3.3
multipledispatch    0.6.0
numpy               1.19.5
opencv-python       4.4.0
Pillow              8.1.0
pip                 20.3.3
PyOpenGL            3.1.5
PyOpenGL-accelerate 3.1.5
pyparsing           2.4.7
PyQt5               5.15.2
PyQt5-sip           12.8.1
pyrr                0.10.3
python-dateutil     2.8.1
setuptools          49.2.1
six                 1.15.0

I know some of these versions don't match up with the requirements you have listed but I'm not sure how to get the older versions.

**Comment by klasrocket** [comment]
hi. quite new to this but I just got it running under linux using this fork: https://github.com/hmikihth/tsugite/
which also contains a requirements file so you could install all dep at once.
you should be able to down grade a specific package using i.e.:
pip3 install opencv-python-headless==4.4.0.46
